# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: gem install bundler
        run: gem install bundler:2.1.4

      - name: bundle init
        run: bundle init
        
      - name: bundle install
        run: bundle install --path vendor/bundle

      - name: add Gemfile
        run: echo gem \"danger\" >> Gemfile
      
      - name: bundle install for added
        run: bundle install
      
      - name: bundle exec danger
        run: bundle exec danger
